### ISSUE TITLE
Intune MAM Compatibility 

### ISSUE THREAD

**Issue by ukanth** [glueckkanja/gk-scepman#1]
Hello,

Thanks for this service. Just wanted to check if this works with intune MAM ? I'm trying to check if we can use this to deliver certificates (2 way SSL) to devices without Enrollment.

Thanks.

**Comment by cekageka** [comment]
I am afraid Intune MAM is not offering Configutation Profiles. That said, you need to switch to MDM if you want to deploy certificates using Intune.

@okieselbach Am I right?

**Comment by okieselbach** [comment]
You're right, no way of pushing config profiles in the MAM without enrollment scenario...

**Comment by ukanth** [comment]
Thanks @cekageka , @okieselbach
