### ISSUE TITLE
Deployment with powershell

### ISSUE THREAD

**Issue by noldersma** [glueckkanja/gk-scepman#2]
Hi

is it possible to deploy the marketplace item SCEPman | Intune SCEP-as-a-Service with a powershell script?

instead of deploying it by hand from the marketplace?

Thanks

**Comment by okieselbach** [comment]
Hi @noldersma,

the package needed for deployment is on the GitHub page and also the ARM template. This is basically all information needed to build a automated deployment via PowerShell. It needs a fair amount of Azure knowledge, but it is totally possible. We don't provide assistance for that, that's not in our support scope for SCEPman.

best,
Oliver

**Comment by noldersma** [comment]
Thanks
