### ISSUE TITLE
Get Thumbprint issued SCEP certificates

### ISSUE THREAD

**Issue by noldersma** [glueckkanja/gk-scepman#3]
Hi

is there a way to retrieve the thumbprints of issued certificates?
Azure VPN gateway does not support a CRL as it seems, you need to add thumbprints for revoked certificates.

regards nathan

**Comment by okieselbach** [comment]
Hi @noldersma,

in Intune there is a Certificate overview unter Home > Devices > Monitor | Certificates here is a list of issued certificates. This API is supported by SCEPman, so certificates issued by SCEPman will be shown there and there is also the Thumbprint. This can also be scripted by using the following graph call:

https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-managedalldevicecertificatestate-get?view=graph-rest-beta

That way you could programmatically build your list of revoked thumbprints..

best,
Oliver

**Comment by noldersma** [comment]
Thanks, found it !
