### ISSUE TITLE
Community edition Marketplace install fails.

### ISSUE THREAD

**Issue by haymansfield** [glueckkanja/gk-scepman#5]
Hi,

I just attempted to install the community edition for evaluation purposes via the marketplace. The Azure deployment works fine, but the site fails to download the site package:

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
<system.webServer>
<rewrite>
<rules>
<rule name = "Site Unavailable" stopProcessing = "true">
<match url = ".*" />
<action type = "CustomResponse" statusCode = "503" subStatusCode = "0" statusReason = "Site Unavailable" statusDescription = "Could not download zip" />
</rule>
</rules>
</rewrite>
</system.webServer>
</configuration>

In addition if I browse the site config I can see a package download url which doesn't work.

Is there anything I can do to resolve or is the marketplace deployment broken?

**Comment by haymansfield** [comment]
I should point out that the github deployment worked fine, but the marketplace option appears to be broken.

**Comment by cekageka** [comment]
Sorry - Marketplace should be fixed. Please open a new one if there's still an issue. Thanks!
