### ISSUE TITLE
Domain Controller Certificates

### ISSUE THREAD

**Issue by sviddal** [glueckkanja/gk-scepman#6]
_**Installation on the Client**
_Then you must download our SCEP client software SCEPClientCore. It requires .NET Core 3.1 to be installed on the target systems.__

Where can I find the SCEP client?

**Comment by cekageka** [comment]
@bb-froggy Could you update the details about preview-access/release date? I am afraid we've added the download info to early... Thanks!

**Comment by okieselbach** [comment]
@sviddal The SCEP client is available in the meantime. Maybe you got already aware of it, if not here is the link: https://github.com/scepman/scepclient

best,
Oliver
