### ISSUE TITLE
SCEPman not able to connect to Intune or get Azure Tennant ID

### ISSUE THREAD

**Issue by AlienET311** [glueckkanja/gk-scepman#7]
Hey, so I'm testing out SCEPman for my Azure setup and followed this guide https://oliverkieselbach.com/2019/07/02/the-easy-way-to-deploy-device-certificates-with-intune/

But after settings the API permissions and  going to the status page I just get this:

![Error](https://user-images.githubusercontent.com/76521562/102996079-b8689b80-4522-11eb-9f36-6953e454f411.PNG)

I've doubled and trippled checked that the API permissions are correct. And I have followed the guide exactly, but still it wont work.

**Comment by okieselbach** [comment]
I followed up via e-Mail.

**Comment by AlienET311** [comment]
With the help of @okieselbach we discovred that this was cause by me settings the wrong Application (client) ID in the CEEPman configuration.
